spring:
  application:
    name: demo18
  security:
    user:
      name: admin_ed
      password: admin_wx13
      roles: ADMIN

server:
  address: 0.0.0.0
  port: 1234

app:
  websocket:
    allowed-origins: "https://yourdomain.com,http://localhost:*,https://localhost:*"

judge:
  auth:
    access-code: "123"
    session-timeout: 30d
    normal-session-timeout: 24h
    max-attempts: 5
    attempt-reset-hours: 1
  
  memory:
    default-limit: 268435456  # 256MB
    max-limit: 1073741824     # 1GB
    check-interval: 100       # ms
  
  compiler:
    default-standard: cpp17
    default-optimization: O2
    timeout: 60s
  
  sandbox:
    enabled: true
    base-directory: /tmp/judge-sandbox
    network-disabled: true
    max-processes: 10

logging:
  level:
    com.example.demo: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG