spring:
  application:
    name: demo18
  security:
    user:
      name: admin_ed
      password: admin_wx13
      roles: ADMIN

server:
  address: 0.0.0.0
  port: 1234

app:
  websocket:
    allowed-origins: "https://yourdomain.com,http://localhost:*,https://localhost:*"

judge:
  auth:
    access-code: "123"
    session-timeout: 30d
    normal-session-timeout: 24h
    max-attempts: 5
    attempt-reset-hours: 1
  
  memory:
    default-limit: 268435456  # 256MB
    max-limit: 1073741824     # 1GB
    check-interval: 100       # ms
  
  compiler:
    default-standard: cpp17
    default-optimization: O2
    timeout: 60s
  
  sandbox:
    enabled: false  # Windows系统下建议禁用沙箱，Linux系统可设为true
    base-directory: C:/temp/judge-sandbox  # Windows路径格式
    network-disabled: true
    max-processes: 10

logging:
  level:
    com.example.demo: INFO  # 改为INFO级别，减少debug输出
    com.example.demo.service.JudgeService: WARN  # 判题服务只记录警告以上
    com.example.demo.service.SandboxService: WARN  # 沙箱服务只记录警告以上
    com.example.demo.service.MemoryMonitorService: WARN  # 内存监控只记录警告以上
    org.springframework.security: WARN  # Spring Security只记录警告
    org.springframework.web.socket: WARN  # WebSocket只记录警告
    org.springframework.messaging: WARN  # 消息框架只记录警告
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/judge-system.log
  logback:
    rolling policy:
      max-file-size: 10MB
      max-history: 30